version: '3'

services:
  app: 
    container_name: docker-node-mongo
    restart: unless-stopped
    build: .
    ports:
      - '8086:8086'
    links:
      - mongo
  mongo: 
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  mmongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    ports:
      - '8081:8081'
